### ISSUE TITLE
Change old name of simatic flow creator to IE Flow Creator

### ISSUE THREAD

**Issue by EndyCZ** [industrial-edge/pingpong-python#3]
The official name has been changed.

https://github.com/industrial-edge/pingpong-python/blob/main/docs/Installation.md

**Comment by HummelN7872** [comment]
please adapt in the documentation

**Comment by HummelN7872** [comment]
#9 Fixed with latest update

**Comment by HummelN7872** [comment]
https://github.com/industrial-edge/pingpong-python/pull/9 Fixed with latest update
